---
engines:
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.coffee"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths: 
- "web/src/inc/react-with-addons-0.13.3.js"
- "web/src/root/js/jquery-ui.min.js"
- "web/src/root/js/jquery.cookie.js"
- "web/src/root/js/jquery.min.js"
- "web/src/root/js/ReactRouter.min.js"
- "web/src/root/js/react.js"
- "web/src/root/js/showdown.min.js"
- "mobile/web/src/root/js/react-with-addons-0.13.3.min.js"
- "mobile/web/src/root/js/ReactRouter.min.js"
- api/src/main/resources/assets/**/*
- web/node_modules/**/*
