language: php

php:
  - 5.4

services:
  - redis-server
  - mysqli

before_script:
  - mysql -u root -e 'create database doorlock;'
  - mysql -u root -e "CREATE USER 'read'@'localhost' IDENTIFIED BY 'PASSWORD';"
  - mysql -u root -e "GRANT SELECT ON doorlock.* TO 'read'@'localhost';"
  - mysql -u root -e "CREATE USER 'write'@'localhost' IDENTIFIED BY 'PASSWORD';"
  - mysql -u root -e "GRANT SELECT, INSERT, UPDATE, CREATE ON doorlock.* TO 'write'@'localhost';"
  - mysql -u root -e "FLUSH PRIVILEGES;"
  - mysql -u root doorlock < createDB.sql
  - mysql -u root -e "show plugins"
  - chmod +x build.sh
  - ./build.sh

script:
  - php -m
  - composer selfupdate
  - cd web
  - composer install
  - phpunit
  - php vendor/bin/coveralls

