language: php

php:
  - 5.4

script: phpunit

before_script:
  - mysql -e 'create database doorlock;'
  - mysql -u root -e "CREATE USER 'read'@'localhost' IDENTIFIED BY 'PASSWORD';"
  - mysql -u root -e "GRANT SELECT ON doorlock.* TO 'read'@'localhost';"
  - mysql -u root -e "CREATE USER 'write'@'localhost' IDENTIFIED BY 'PASSWORD';"
  - mysql -u root -e "GRANT SELECT, INSERT, UPDATE, CREATE ON doorlock.* TO 'write'@'localhost';"
  - mysql -u root -e "FLUSH PRIVILEGES;"
  - mysqldump -u root doorlock > createDB.sql
  - chmod +x build.sh
  - ./build.sh

services:
  - redis-server
