FORMAT: 1A
HOST: http://api.doorlock.wrixton.net/

# Door Lock
This is the API for a door lock system.
It handles all information that is transferred to the system.


# Group Login
Login to doorlock. Handles login and session management.

## GET /login
Returns login information, sets a cookie if the passed in data is valid.
Also returns success = 1 for success. Returns success = 0 for fail.
+ Request (application/json)
   
    + Headers 
 
            X-DoorLock-Api-Key: {Api-Key}

    + Body
    
            {
                "username": "{user}",
                "password": "{pass}"
            }

+ Response 200 (application/json)
    
    + Headers
        
            Set-Cookie: sid={cookie}; path=/;

    + Body
    
            {
                "username": "{user}",
                "success": 1
            }

+ Response 401 (application/json)

    + Body
    
            {
                "Invalid API key": "{Api-Key}",
                "success": 0
            }
            
+ Response 403 (application/json)

    + Body
    
            {
                "Invalid Username or Password": "{Username}",
                "success": 0
            }
            
            
            
# Group Logout
Logs out of the doorlock. Handles logout and session management.

## GET /logout
Returns logout information, sets a cookie if the passed in data is valid.
Also returns success = 1 for success. Returns success = 0 for fail.
+ Request (application/json)
   
    + Headers 
 
            X-DoorLock-Api-Key: {Api-Key}


    + Body
    
            {
                "username": "{user}",
                "cookie": "{sid}"
            }

+ Response 200 (application/json)

    + Body
    
            {
                "Logged out": "{user}",
                "success": 1
            }
